In [2]:
map_box_to_coordinates_100 = {}
x = 0
y = 0
k = 0
while y <= 756:
    x = 0
    while x <= 1355:
        map_box_to_coordinates_100[k] = {'x':[x, x+99], 'y':[y, y+99]}
        x += 100
        k += 1
    y += 100
map_box_to_coordinates_100

{0: {'x': [0, 99], 'y': [0, 99]},
 1: {'x': [100, 199], 'y': [0, 99]},
 2: {'x': [200, 299], 'y': [0, 99]},
 3: {'x': [300, 399], 'y': [0, 99]},
 4: {'x': [400, 499], 'y': [0, 99]},
 5: {'x': [500, 599], 'y': [0, 99]},
 6: {'x': [600, 699], 'y': [0, 99]},
 7: {'x': [700, 799], 'y': [0, 99]},
 8: {'x': [800, 899], 'y': [0, 99]},
 9: {'x': [900, 999], 'y': [0, 99]},
 10: {'x': [1000, 1099], 'y': [0, 99]},
 11: {'x': [1100, 1199], 'y': [0, 99]},
 12: {'x': [1200, 1299], 'y': [0, 99]},
 13: {'x': [1300, 1399], 'y': [0, 99]},
 14: {'x': [0, 99], 'y': [100, 199]},
 15: {'x': [100, 199], 'y': [100, 199]},
 16: {'x': [200, 299], 'y': [100, 199]},
 17: {'x': [300, 399], 'y': [100, 199]},
 18: {'x': [400, 499], 'y': [100, 199]},
 19: {'x': [500, 599], 'y': [100, 199]},
 20: {'x': [600, 699], 'y': [100, 199]},
 21: {'x': [700, 799], 'y': [100, 199]},
 22: {'x': [800, 899], 'y': [100, 199]},
 23: {'x': [900, 999], 'y': [100, 199]},
 24: {'x': [1000, 1099], 'y': [100, 199]},
 25: {'x': [1100, 1199]

In [3]:
len(map_box_to_coordinates_100)

112

In [4]:
from tkinter import * 

frame = Tk()  
frame.attributes('-fullscreen',True) 

myCanvas = Canvas(frame)
myCanvas.pack(fill=BOTH, expand=True)
for key in map_box_to_coordinates_100.keys():
    x = map_box_to_coordinates_100[key]['x'][0]
    y = map_box_to_coordinates_100[key]['y'][0]
    box = myCanvas.create_rectangle(x, y, x+100, y+100, outline="#000000")
frame.mainloop()

In [1]:
import os
import pandas as pd
import numpy as np

In [7]:
IMG_SIZE = 100
training = []
x = [] #features
y = [] #labels
cord_x = []
cord_y = []
box = []
source = 'left_eyes_data'
for filename in os.listdir(source):
    string = filename.split(".")
#     img = cv2.imread(os.path.join(source,filename))
#     x.append(img)
    x_coord = int(string[0])
    y_coord = int(string[1]) 
    box_no = 14*(y_coord//100) + (x_coord//100)
    cord_x.append(x_coord)
    cord_y.append(y_coord)
    box.append(box_no)
#     y.append([int(string[0]), int(string[1])])
#     training.append([img, [int(string[0]), int(string[1])]])
print(cord_x)
print(cord_y)
print(box)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 10, 10, 10, 10, 10, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1001, 1001, 1001, 1002, 1002, 1002, 1002, 1002, 1002, 1002, 1003, 1003, 1003, 1004, 1004, 1004, 1005, 1005, 1005, 1005, 1005, 1005, 1006, 1006, 1006, 1006, 1006, 1006, 1006, 1007, 1007, 1007, 1008, 1008, 1008, 1008, 1008, 1008, 1008, 1008, 1009, 1009, 1009, 1009, 1009, 101, 101, 101, 101, 1010, 1010, 1010, 1010, 1011, 1011, 1011, 1011, 1011, 1011, 1012, 1

In [8]:
df = pd.DataFrame()

In [9]:
df['x'] = cord_x

In [10]:
df['y'] = cord_y

In [11]:
df['box'] = box

In [12]:
df['box'].value_counts()

0      306
2      295
8      280
1      278
3      274
      ... 
97      39
69      38
27      37
83      36
111     29
Name: box, Length: 112, dtype: int64

In [13]:
df.head(20)

x    y  box
0   0    0    0
1   0    0    0
2   0    1    0
3   0  100   14
4   0  120   14
5   0  140   14
6   0  180   14
7   0   20    0
8   0  200   28
9   0  220   28
10  0  234   28
11  0  240   28
12  0  260   28
13  0  280   28
14  0  300   42
15  0  320   42
16  0  340   42
17  0  360   42
18  0  380   42
19  0   40    0

In [15]:
df.to_excel('data.xlsx')

In [16]:
import cv2
from keras.utils import np_utils
from sklearn.model_selection import train_test_split

In [17]:
IMG_SIZE = 100
# training = []
x = [] #features
y = [] #labels
source = 'left_eyes_data'
for filename in os.listdir(source):
    string = filename.split(".")
    img = cv2.imread(os.path.join(source,filename))
    img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    x.append(img)
    x_coord = int(string[0])
    y_coord = int(string[1]) 
    box_no = 14*(y_coord//100) + (x_coord//100)
    y.append(box_no)
#     training.append([img, box_no])
print(x)
print(y)
# print(training)

[array([[ 78,  77,  76, ...,  78,  80,  81],
       [ 77,  76,  75, ...,  77,  79,  80],
       [ 76,  75,  73, ...,  75,  76,  77],
       ...,
       [111, 111, 112, ..., 105, 104, 104],
       [112, 112, 113, ..., 106, 105, 105],
       [113, 113, 114, ..., 106, 105, 105]], dtype=uint8), array([[ 72,  72,  71, ...,  78,  79,  80],
       [ 72,  71,  70, ...,  77,  79,  80],
       [ 70,  70,  69, ...,  77,  78,  79],
       ...,
       [105, 105, 105, ...,  88,  89,  89],
       [104, 105, 105, ...,  89,  89,  89],
       [105, 105, 105, ...,  89,  89,  89]], dtype=uint8), array([[ 64,  64,  64, ...,  80,  80,  79],
       [ 65,  65,  65, ...,  80,  79,  79],
       [ 66,  67,  67, ...,  80,  80,  79],
       ...,
       [104, 105, 105, ...,  82,  82,  82],
       [105, 105, 106, ...,  83,  83,  83],
       [106, 106, 106, ...,  83,  83,  83]], dtype=uint8), array([[ 90,  89,  88, ..., 111, 112, 113],
       [ 90,  89,  88, ..., 110, 111, 112],
       [ 89,  88,  88, ..., 108, 109, 

In [19]:
from sklearn.utils import shuffle

x, y = shuffle(x, y)

In [20]:
x = np.array(x).reshape(len(x), 100, 100, 1)
x = x.astype('float32')
x /= 255
x

array([[[[0.28235295],
         [0.28235295],
         [0.28235295],
         ...,
         [0.31764707],
         [0.32156864],
         [0.32156864]],

        [[0.28235295],
         [0.28235295],
         [0.28235295],
         ...,
         [0.31764707],
         [0.32156864],
         [0.32156864]],

        [[0.28235295],
         [0.28235295],
         [0.28235295],
         ...,
         [0.31764707],
         [0.32156864],
         [0.3254902 ]],

        ...,

        [[0.41960785],
         [0.41960785],
         [0.41960785],
         ...,
         [0.4       ],
         [0.39607844],
         [0.39607844]],

        [[0.42352942],
         [0.41960785],
         [0.41960785],
         ...,
         [0.4       ],
         [0.39607844],
         [0.4       ]],

        [[0.42352942],
         [0.42352942],
         [0.42352942],
         ...,
         [0.4       ],
         [0.4       ],
         [0.4       ]]],


       [[[0.627451  ],
         [0.6313726 ],
         [0.63

In [21]:
y = np_utils.to_categorical(y, dtype ="uint8")

In [22]:
y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [24]:
x_train.shape

(7942, 100, 100, 1)

In [25]:
y_train.shape

(7942, 112)

In [26]:
x_test.shape

(1986, 100, 100, 1)

In [27]:
y_test.shape

(1986, 112)

In [28]:
from keras.models import Sequential
from keras.layers import Dense, Conv2D, Flatten, MaxPool2D, Dropout
import tensorflow as tf

In [29]:
model = Sequential()
model.add(Conv2D(50, kernel_size=(3,3), strides=(1,1), padding='same', activation='relu', input_shape=(100, 100, 1)))

# convolutional layer
model.add(Conv2D(75, kernel_size=(3,3), strides=(1,1), padding='same', activation='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Conv2D(125, kernel_size=(3,3), strides=(1,1), padding='same', activation='relu'))
model.add(MaxPool2D(pool_size=(2,2)))
model.add(Dropout(0.25))

# flatten output of conv
model.add(Flatten())

# hidden layer
model.add(Dense(500, activation='relu'))
model.add(Dropout(0.4))
model.add(Dense(250, activation='relu'))
model.add(Dropout(0.3))
# output layer
model.add(Dense(112, activation='softmax'))

In [30]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [31]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=3)

Epoch 1/3
249/249 [==============================] - 2426s 10s/step - loss: 4.6135 - accuracy: 0.0301 - val_loss: 4.5480 - val_accuracy: 0.0302
Epoch 2/3
249/249 [==============================] - 3003s 12s/step - loss: 4.5024 - accuracy: 0.0306 - val_loss: 4.2717 - val_accuracy: 0.0307
Epoch 3/3
249/249 [==============================] - 3553s 14s/step - loss: 4.1150 - accuracy: 0.0614 - val_loss: 3.8320 - val_accuracy: 0.1002


In [125]:
model.predict(x_test[:4])

array([[0.0095376 , 0.00950584, 0.0108806 , 0.00965426, 0.00929476,
        0.00874724, 0.00925654, 0.00938988, 0.00915341, 0.0096879 ,
        0.00864973, 0.0090257 , 0.00943038, 0.00760755, 0.00942323,
        0.00877554, 0.00937883, 0.00892802, 0.01019509, 0.00925625,
        0.00954835, 0.00918146, 0.00834821, 0.00949448, 0.00806884,
        0.00861749, 0.00869567, 0.00724151, 0.00971767, 0.01014991,
        0.00936822, 0.00988454, 0.00879578, 0.00962666, 0.00925046,
        0.00945897, 0.00939526, 0.00845924, 0.00877322, 0.0082947 ,
        0.00786327, 0.00829096, 0.00933273, 0.01000426, 0.00993579,
        0.00924713, 0.00919168, 0.00942424, 0.00947162, 0.00867231,
        0.00968222, 0.00934739, 0.00916369, 0.00893462, 0.00893129,
        0.00866043, 0.00928336, 0.01043487, 0.0099872 , 0.00914029,
        0.00935809, 0.00906684, 0.00870649, 0.00886632, 0.00897659,
        0.00887954, 0.008914  , 0.00882225, 0.00895579, 0.0073061 ,
        0.00877735, 0.00857921, 0.00932479, 0.00

In [126]:
y_test[:4]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        

In [ ]:
model_json = model.to_json()
with open("CNNmodel.json", "w") as json_file:
    json_file.write(model_json)

model.save_weights("CNNmodel.h5")
print("Saved model to disk")